name: CI/CD Pipeline
# This workflow is triggered on pushes to the repository.
on: push

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Run Tests
              run: scripts/validator.sh
    build-publish:
        name: Build & Publish
        needs: test
        # only run this on qa & prod branches
        if: github.ref == 'refs/heads/qa' || github.ref == 'refs/heads/prod'
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Build Docker Image & Push to GitHub Packages
              uses: docker/build-push-action@v1
              with:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
                registry: docker.pkg.github.com
                repository: openshiksha/openshiksha-cabinet/openshiksha-cabinet
                tag_with_ref: true
                tag_with_sha: true
    deploy-qa:
        name: Deploy to QA Cluster
        needs: build-publish
        # only run this on qa branch
        if: github.ref == 'refs/heads/qa'
        runs-on: ubuntu-latest
        steps:
            - name: Setup Gcloud CLI
            uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
            with:
              version: '290.0.1'
              service_account_key: ${{ secrets.GKE_QA_SA_KEY }}
              project_id: ${{ secrets.GKE_QA_PROJECT_ID }}

            - name: Fetch Cluster KubeConfig
              run: |-
                gcloud container clusters get-credentials ${{ secrets.GKE_QA_CLUSTER_NAME }} --zone ${{ secrets.GKE_QA_ZONE_ID }}
            - name: Restart statefulset
              run: kubectl rollout restart statefulset ${{ secrets.GKE_QA_CLUSTER_RELEASE }}-openshiksha-cabinet
    deploy-prod:
        name: Deploy to PROD Cluster
        needs: build-publish
        # only run this on prod branch
        if: github.ref == 'refs/heads/prod'
        runs-on: ubuntu-latest
        steps:
            - name: Setup Gcloud CLI
              uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
              with:
                version: '290.0.1'
                service_account_key: ${{ secrets.GKE_PROD_SA_KEY }}
                project_id: ${{ secrets.GKE_PROD_PROJECT_ID }}

            - name: Fetch Cluster KubeConfig
              run: |-
                gcloud container clusters get-credentials ${{ secrets.GKE_PROD_CLUSTER_NAME }} --zone ${{ secrets.GKE_PROD_ZONE_ID }}
            - name: Restart statefulset
              run: kubectl rollout restart statefulset ${{ secrets.GKE_PROD_CLUSTER_RELEASE }}-openshiksha-cabinet